// <auto-generated />
namespace CoachSportif.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gestion_Admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gestion_Admin));
        
        string IMigrationMetadata.Id
        {
            get { return "202111041347498_Gestion_Admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
